# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name=b'start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name=b'end_time')),
                ('description', models.CharField(max_length=1024)),
                ('break_duration_minutes', models.IntegerField(default=0)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.Project')),
            ],
        ),
    ]
