# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslice',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='timeslice',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start time'),
        ),
    ]
