# Generated by Django 2.0.4 on 2018-04-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_auto_20160522_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timetracker.Project'),
        ),
    ]
