# Generated by Django 4.2.3 on 2023-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_auto_20180411_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslice',
            name='is_checked_after_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslice',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
