app:
  build: .
  ports:
    - "7777:8000"
  links:
    - postgres
  volumes_from:
    - data
data:
  #image:
  #command: echo 'Data Container for PostgreSQL'
  volumes:
    - /opt/freelance-organizer