# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_crm.BaseModel')),
                ('short_description', models.CharField(max_length=80)),
            ],
            bases=('simple_crm.basemodel',),
        ),
        migrations.CreateModel(
            name='BusinessOpportunity',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_crm.BaseModel')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_realized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'last_changed'],
            },
            bases=('simple_crm.basemodel',),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_crm.BaseModel')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=80)),
                ('xing_url', models.URLField(blank=True, max_length=80)),
                ('web_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=42)),
                ('skype_name', models.CharField(blank=True, max_length=42)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'company_name'],
            },
            bases=('simple_crm.basemodel',),
        ),
        migrations.AddField(
            model_name='businessopportunity',
            name='contact_person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simple_crm.ContactPerson'),
        ),
        migrations.AddField(
            model_name='activity',
            name='business_opportunity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simple_crm.BusinessOpportunity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='simple_crm.ContactPerson'),
        ),
    ]
