version: "3.9"
name: freelance-organizer
services:
  prod-app:
    image: freelance-organizer:production
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ../../prod-db:/var/lib/freelance-organizer
  dev-app:
    image: freelance-organizer:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9999:9000"
    volumes:
      - ../../dev-db:/var/lib/freelance-organizer
