version: "3.9"
services:
  freelance-organizer-prod:
    image: freelance-organizer:production
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ../../prod-db:/var/lib/freelance-organizer
  freelance-organizer-dev:
    image: freelance-organizer:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9999:9000"
    volumes:
      - ../../dev-db:/var/lib/freelance-organizer
