# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_time', models.DateTimeField()),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(max_length=140)),
                ('reason', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, null=True)),
                ('free_days', models.IntegerField(default=0)),
                ('hotel_stay_with_breakfast', models.BooleanField(default=False)),
            ],
        ),
    ]
